adsEndPoints = {
    "/api2/ad/external/get":
    [
        {
            "urls":
            [
                "array",
                "http://uplynk.s3.amazonaws.com/test/Oreo.mp4;http://ads.s3.amazonaws.com/Choco.mp4"
            ]
        }
    ],
    "/api/v3/adproxy/ad-debug/jobs":
    [
        {
            "channel_guid":
            [
                "str",
                "12a60a37dec047b2972lb29b60218f90"
            ]
        },
        {
            "debug_name":
            [
                "str",
                "campaign2"
            ]
        },
        {
            "end":
            [
                "str",
                "2022-01-08T20:31:11.510000Z"
            ]
        },
        {
            "includes":
            [
                "str",
                "transactions,callbacks,ads_info"
            ]
        },
        {
            "playback_type":
            [
                "str",
                "live (or) vod"
            ]
        },
        {
            "start":
            [
                "str",
                "2022-01-08T20:31:11.510000Z"
            ]
        },
        {
            "status":
            [
                "str",
                "Completed / failed / Pending / Processing"
            ]
        },
        {
            "video_guid":
            [
                "str",
                "34a60a37dec047b2972lb29b60218f90"
            ]
        },
        {
            "viewer_guid":
            [
                "str",
                "(viewer session"
            ]
        }
    ]
}