assetEndPoints = {
    "/api2/asset/get":
    [
        {
            "id":
            [
                "str",
                "12a60a37dec047b2972lb29b60218f90",
                "0"
            ]
        },
        {
            "external_id":
            [
                "str",
                "SportsClip",
                "0"
            ]
        },
        {
            "ids":
            [
                "array",
                "12a60a37dec047b2972lb29b60218f90;8c01b75a17254b8da076bcc98c7f0829",
                "0"
            ]
        },
        {
            "external_ids":
            [
                "array",
                "SportsClip;NewsClip",
                "0"
            ]
        }
    ],
    "/api2/asset/update":
    [
        {
            "id":
            [
                "str",
                "12a60a37dec047b2972lb29b60218f90"
            ]
        },
        {
            "external_id":
            [
                "str",
                "SportsClip"
            ]
        },
        {
            "desc":
            [
                "string",
                "Team Highlights 2022"
            ]
        },
        {
            "require_drm":
            [
                "int",
                "0 or 1"
            ]
        },
        {
            "require_studio_drm":
            [
                "int",
                "0 or 1"
            ]
        },
        {
            "meta":
            [
                "obj",
                "Description:PromoVideo;Genre:Sports"
            ]
        },
        {
            "test_player_url":
            [
                "any",
                "1"
            ]
        },
        {
            "embed_player_url":
            [
                "string",
                "1"
            ]
        }
    ],
    "/api2/asset/delete":
    [
        {
            "ids":
            [
                "array",
                "12a60a37dec047b2972lb29b60218f90;8c01b75a17254b8da076bcc98c7f0829",
                "0"
            ]
        },
        {
            "external_ids":
            [
                "array",
                "SportsClip;NewsClip",
                "0"
            ]
        }
    ],
    "/api2/asset/changes":
    [
        {
            "start":
            [
                "int",
                "8.5  (8 and a half HOURS ago)"
            ]
        }
    ],
    "/api2/asset/getframe":
    [
        {
            "id":
            [
                "str",
                "12a60a37dec047b2972lb29b60218f90"
            ]
        },
        {
            "ts":
            [
                "int",
                "600.000 (10min in seconds)"
            ]
        }
    ],
    "/api2/asset/getthumbs":
    [
        {
            "id":
            [
                "str",
                "12a60a37dec047b2972lb29b60218f90"
            ]
        },
        {
            "start":
            [
                "int",
                "60.000 (60 seconds)"
            ]
        },
        {
            "stop":
            [
                "int",
                "61.000 (61 seconds - max 1 second)" 
            ]
        }
    ],
    "/api2/asset/list":
    [
        {
            "ignore_shared_libraries":
            [
                "bool",
                "1"
            ]
        },
        {
            "limit":
            [
                "int",
                "100 (default)"
            ]
        },
        {
            "order":
            [
                "str",
                "(created | desc | duration | external_id | id | lastmod | source | state)"
            ]
        },
        {
            "skip":
            [
                "int",
                "0" 
            ]
        },
        {
            "query":
            [
                "str",
                "news*" 
            ]
        }
    ]
}