cloudSlicerEndPoints = {
    "/api2/cloudslicer/jobs/get":
    [
        {
            "id":
            [
                "str",
                "0p4b17c8710f4b7da4a460893fdc5062"
            ]
        }
    ],
    "/api2/cloudslicer/jobs/delete":
    [
        {
            "ids":
            [
                "array",
                "0p4b17c8710f4b7da4a460893fdc5062;901gtac7f9634672b78153c130f27020"
            ]
        }
    ],
    "/api2/cloudslicer/jobs/list":
    [
        {
            "limit":
            [
                "int",
                "50 (50 jobs)"
            ]
        },
        {
            "skip":
            [
                "int",
                "50 (skip 50 to see next 50)"
            ]
        }
    ],
    "/api2/cloudslicer/jobs/create":
    [
        {
            "args":
            [
                "obj",
                "description:Tears of Steel;\nexternal_id:tears_of_steel;\ntrim:0,180000;\nmeta:genre=action,,,license=open_source;\nslicer_args:-audiodesc \"English\" -atrack 0"
            ]
        },
        {
            "source":
            [
                "obj",
                "http://wpc.10776.edgecastcdn.net/0010776/samplefiles/tears_of_steel_1080p.mov"
            ]
        },
        {
            "high_priority":
            [
                "int",
                "0  or  1   ( NEW FEATURE UNTESTED )"
            ]
        }
    ],
    "/api2/cloudslicer/jobs/quickclip":
    [
        {
            "args":
            [
                "obj",
                "beam_id:278b58b245b741078c3d5c9da3f871ef"
            ]
        },
        {
            "source":
            [
                "obj",
                "60,240.500  (60000 to 240500 seconds)"
            ]
        }
    ],
    "/api2/cloudslicer/jobs/create_export":
    [
        {
            "asset":
            [
                "str",
                "12a60a37dec047b2972lb29b60218f90"
            ]
        }
    ],
    "/api2/cloudslicer/jobs/cancel":
    [
        {
            "id":
            [
                "str",
                "0p4b17c8710f4b7da4a460893fdc5062"
            ]
        }
    ],
    "/api2/cloudslicer/jobs/copy-from-library":
    [
        {
            "asset_id":
            [
                "str",
                "12a60a37dec047b2972lb29b60218f90"
            ]
        }
    ],
    "/api2/cloudslicer/batch/copy-from-library":
    [
        {
            "asset_ids":
            [
                "array",
                "12a60a37dec047b2972lb29b60218f90;8c01b75a17254b8da076bcc98c7f0829"
            ]
        }
    ],
    "/api2/cloudslicer/batch/get-job-states":
    [
        {
            "id":
            [
                "str",
                "89bgha37dec047b2972lb29b60218f90  (ID of batch 'copy-from-library' Job"
            ]
        }
    ],
    "/api2/cloudslicer/jobs/add_track_audio":
    [
        {
            "api_key":
            [
                "str",
                "(AWS S3 API Key)"
            ]
        },
        {
            "api_secret":
            [
                "str",
                "(AWS S3 Secret"
            ]
        },
        {
            "asset":
            [
                "str",
                "12a60a37dec047b2972lb29b60218f90"
            ]
        },
        {
            "desc":
            [
                "str",
                "Spanish"
            ]
        },
        {
            "dolby":
            [
                "int",
                "0 (generates AAC track) 1 (generates DDP & AAC tracks"
            ]
        },
        {
            "lang":
            [
                "str",
                "spa"
            ]
        },
        {
            "url":
            [
                "str",
                "http://myserver.com/path/to/file.mp4 (OR) s3://Endpoint/Bucket/KeyName"
            ]
        },
        {
            "source":
            [
                "obj",
                "(ADV:multiple:use 'asset','source' only.Source is Obj + all values-UNTESTED!)"
            ]
        }
    ],
    "/api2/cloudslicer/jobs/add_track_vtt":
    [
        {
            "api_key":
            [
                "str",
                "(AWS S3 API Key)"
            ]
        },
        {
            "api_secret":
            [
                "str",
                "(AWS S3 Secret"
            ]
        },
        {
            "asset":
            [
                "str",
                "12a60a37dec047b2972lb29b60218f90"
            ]
        },
        {
            "default_position":
            [
                "str",
                "left (left | center | right)"
            ]
        },
        {
            "default_vertcal":
            [
                "str",
                "top (top | center | bottom)"
            ]
        },
        {
            "desc":
            [
                "str",
                "Spanish"
            ]
        },
        {
            "lang":
            [
                "str",
                "spa"
            ]
        },
        {
            "subtitle_absolute_time":
            [
                "int",
                "0 (mapped relative to timestamp) 1 (absolute time mapping)"
            ]
        },
        {
            "ttml_data":
            [
                "str",
                "(Base64-encoded TTML data, first track will be added)"
            ]
        },
        {
            "ttml_url":
            [
                "str",
                "http://server.com/path/to/Sub.ttml (OR) s3://S3Endpoint/Bucket/KeyName"
            ]
        },
        {
            "source":
            [
                "obj",
                "(ADV:add multiple:use 'asset','source' only.Source is list of Obj-UNTESTED)"
            ]
        }
    ],
    "/api2/cloudslicer/jobs/replace_track_vtt":
    [
        {
            "api_key":
            [
                "str",
                "(AWS S3 API Key)"
            ]
        },
        {
            "api_secret":
            [
                "str",
                "(AWS S3 Secret"
            ]
        },
        {
            "asset":
            [
                "str",
                "12a60a37dec047b2972lb29b60218f90"
            ]
        },
        {
            "default_position":
            [
                "str",
                "left (left | center | right)"
            ]
        },
        {
            "default_vertcal":
            [
                "str",
                "top (top | center | bottom)"
            ]
        },
        {
            "desc":
            [
                "str",
                "Spanish"
            ]
        },
        {
            "lang":
            [
                "str",
                "spa"
            ]
        },
        {
            "subtitle_absolute_time":
            [
                "int",
                "0 (mapped relative to timestamp) 1 (absolute time mapping)"
            ]
        },
        {
            "track_num":
            [
                "int",
                "0 (zero-based index number Identifying track to be replaced)"
            ]
        },
        {
            "ttml_data":
            [
                "str",
                "(Base64-encoded TTML data, first track will be added)"
            ]
        },
        {
            "ttml_url":
            [
                "str",
                "http://server.com/path/to/Sub.ttml (OR) s3://S3Endpoint/Bucket/KeyName"
            ]
        },
        {
            "source":
            [
                "obj",
                "(ADV: replace multiple tracks, 'asset','source' field only. List of Obj)"
            ]
        }
    ]
}