cloudSlicerEndPoints = {
    "/api2/cloudslicer/jobs/get":
    [
        {
            "id":
            [
                "str",
                "0p4b17c8710f4b7da4a460893fdc5062"
            ]
        }
    ],
    "/api2/cloudslicer/jobs/list":
    [
        {
            "limit":
            [
                "int",
                "50 (50 jobs)"
            ]
        },
        {
            "skip":
            [
                "int",
                "50 (skip 50 to see next 50)"
            ]
        }
    ],
    "/api2/cloudslicer/jobs/create":
    [
        {
            "args":
            [
                "obj",
                "description:My file description;external_id:new test video;meta:genre=action,,,key=value"
            ]
        },
        {
            "source":
            [
                "obj",
                "http://wpc.edgecastcdn.net/samplefiles/test.mp4"
            ]
        }
    ],
    "/api2/cloudslicer/jobs/quickclip":
    [
        {
            "args":
            [
                "obj",
                "beam_id:278b58b245b741078c3d5c9da3f871ef"
            ]
        },
        {
            "source":
            [
                "obj",
                "60,240.500  (60000 to 240500 milliseconds"
            ]
        }
    ],
    "/api2/cloudslicer/jobs/create_export":
    [
        {
            "asset":
            [
                "str",
                "12a60a37dec047b2972lb29b60218f90"
            ]
        }
    ],
    "/api2/cloudslicer/jobs/copy-from-library":
    [
        {
            "asset_id":
            [
                "str",
                "12a60a37dec047b2972lb29b60218f90"
            ]
        }
    ],
    "/api2/cloudslicer/batch/copy-from-library":
    [
        {
            "asset_ids":
            [
                "array",
                "12a60a37dec047b2972lb29b60218f90;8c01b75a17254b8da076bcc98c7f0829"
            ]
        }
    ],
    "/api2/cloudslicer/batch/get-job-states":
    [
        {
            "id":
            [
                "str",
                "89bgha37dec047b2972lb29b60218f90  (ID of batch 'copy-from-library' Job"
            ]
        }
    ]
}