slicerEndPoints = {
    "/api2/slicer/status":
    [
        {
            "slicer_ids":
            [
                "array",
                "my_slicer_1;my_slicer_2"
            ]
        }
    ],
    "/api2/slicer/schedule/get":
    [
        {
            "slicer_id":
            [
                "str",
                "my_slicer_1"
            ]
        }
    ],
    "/api2/slicer/schedule/update":
    [
        {
            "schedule":
            [
                "obj",
                ""
            ]
        },
        {
            "slicer_id":
            [
                "str",
                ""
            ]
        },
        {
            "update_start":
            [
                "str",
                ""
            ]
        },
        {
            "update_end":
            [
                "str",
                ""
            ]
        },
        {
            "utc_offset":
            [
                "int",
                ""
            ]
        },
        {
            "wallclock":
            [
                "int",
                ""
            ]
        }
    ]
}